### ISSUE TITLE
Using fixtures from live networks in the tests for transactions, cryptography

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-elements#618]
### Description
Transactions and cryptography are hard to tell if it's correct or not.
Source of truth is existing data on network, so we should take that to check the test

**Expected behavior:
Using the fixture to check if the produced result is correct or not.

### Versions
v1.0.0

### Additional Information
Issues like #616, can be caught with this

**Comment by Tosch110** [comment]
How do you imagine that works? 
I have thought of ways to do that but in order to recreate and sign transactions you would need access to passphrases. On testnet we could just run the verify function through all the transactions but we would not be able to recreate signatures and compare or any of that logic.

What do you have in mind if you could elaborate?

**Comment by shuse2** [comment]
I think what we need is just one cases for each one as `fixture`.
Mainly for checking if the functionality has not changed over time. (assuming the fixture is correct)
So, create each transaction with know account in devnet, and use it for the test?

**Comment by shuse2** [comment]
@willclarktech 
I think this issue is invalid although Im the one created ='(
- Even though we take transactions from the network, we don't have passphrase to check.
- Already using fixtures to test where it can
- getBytes methods is the intermediate product, so it's not possible to check against the fixture
