### ISSUE TITLE
Add prefix to signed message

### ISSUE THREAD

**Issue by alepop** [LiskHQ/lisk-elements#673]
### Description
Lisk signed message don't have prefix bytes in the header. This may cause next type of errors:
1) It can sign whatever you give to message signing function, even a transaction digest.
2) It can verify a signature from a separate coin with the same curve.

### Steps to Reproduce

1. Sign message with another ed25519 curve implementation
2. Verify it with `lisk-elements`

**Expected behavior:**

Message signing adds specific for Lisk prefix bytes to the signed message.

**Actual behavior:** 

No prefix

**Reproduces how often:** 

Constantly

### Versions

`1.0.0`

### Additional Information
From Ethereum repos:

> By adding a prefix to the message makes the calculated signature recognisable as an Ethereum
> specific signature. This prevents misuse where a malicious DApp can sign arbitrary data (e.g. transaction) and use the signature to impersonate the victim.

**Comment by willclarktech** [comment]
@alepop Thanks for this, we'll arrange a meeting to establish the best way forward here as this has implications for front end applications/backward compatibility.

**Comment by alepop** [comment]
@willclarktech also, all most popular coins use a hash algorithm for signed messages before sign it. 
The whole hash looks similar to this before passing to sign function:
```
h = hash_algorithm_function 
result = h(varint(len(prefix))) + h(prefix) + h(varint(len(message))) + h(message)
```
Then `result` passed to the sign function. What about implement something like this with sha256?

**Comment by willclarktech** [comment]
## Update from meeting today

This is something we want to address and we will include a solution in the release for 1.0.0 since we have breaking changes in the elements function then already. Users have a responsibility to check what they are signing, but in the interests of usability this can be an important barrier to a certain class of user manipulation attempts.

Since signatures are usually intended for single-use situations, and this is a security-related issue, we aren't planning to provide backwards compatibility.

### Issues to investigate

1. Whether we should be hashing the message before signing and why?
1. Whether there's an advantage to including the lengths of the prefix and/or message itself?
1. How this relates to https://github.com/LiskHQ/lisk/issues/1610 because poor coordination between these two issues could reintroduce replay attacks (e.g. if we opt for a prefix-based solution to both and the prefixes are related to each other in the wrong ways).

**Comment by IkerAlus** [comment]
Some conclusions after studying the issue:

### Regarding 1: 
In general, hashing before signing is the "standard" procedure. However, the main reason to hash before signing is essentially the performance. It makes no sense to sign a whole large document. It is true also that there are [some vulnerabilities](https://crypto.stackexchange.com/questions/12768/why-hash-the-message-before-signing-it-with-rsa) connected to not hashing the message (when RSA is used and the message is big enough). At the moment, in our [current code](https://github.com/LiskHQ/lisk-elements/blob/development/src/cryptography/sign.js#L27), there is no hashing, nor size limit for the message (but we use elliptic curve signatures).

More interestingly, I believe that not hashing the message will solve the potential problem with the third point. By skipping the hashing step in the message signing function, we will introduce a fundamental difference between this and the transaction signing process. An attacker could not be able to get a malicious transaction signed by a third party: the prefix attached to the transaction hash will make the transaction invalid and this attack unfeasible.

### Regarding 2:
I cannot see any (security) advantage of including lengths in the message to sign, specially if there is no hashing of the message. The only thing I can think of is the extra info provided to the signer/verifier about the lengths of the different parts of the signed data.

### Regarding 3: 
See first point.

## Conclusion:
Although it may not be perfectly orthodox, we can easily solve issues in points 1 and 3 by imposing a comprehensive message size and not hashing before signing. Therefore, **my proposal** will be to add a size constraint to the message and then attach a constant and basic prefix to the message. Once this is done, the message is signed.

**Comment by alepop** [comment]
@IkerAlus hi! which constant? And what message limit?  And how data may look at the end before signing? 
`prefix + constant? + message`

**Comment by willclarktech** [comment]
Another way to get the advantages of hashing while still retaining a fundamental difference between signing messages and signing transactions would be to hash messages twice, rather than 0 times. (Or to use a different hashing algorithm).

**Comment by IkerAlus** [comment]
@alepop "constant" as an adjective, not a noun. Let me re-write that part:
"to add a size constraint to the message and then attach a fixed prefix to the message" so it will be:
`prefix + message`
I cannot see a clear use case to sign a big file with "Lisk specific" software. But perhaps @willclarktech  or @slaweet have a different opinion. In that case, we will need to hash the message as normal, and think about the impact of point 3 from Will.

@willclarktech  Definitely, hashing twice will have same properties and it is a **much more** elegant solution.  Perfect!

Therefore, with this last idea, the output `result` from the third post will be generated as:

`result = h(h(prefix + message))`

This will imply that:

- Signatures are unique to the Lisk ecosystem
- No size constraint for message is needed.
- Fundamentally different to signing transactions

**Comment by alepop** [comment]
@willclarktech @IkerAlus `h = sha256`?

**Comment by IkerAlus** [comment]
@alepop yes, for simplicity.

**Comment by willclarktech** [comment]
> I cannot see any (security) advantage of including lengths in the message to sign, specially if there is no hashing of the message

@IkerAlus Now that we do have hashing of the message, should we be including the lengths?

**Comment by IkerAlus** [comment]
After browsing several Bitcoin forums, the conclusion is: **Yes**. We should include both lengths.

The [standard Bitcoin message signature](https://bitcoin.stackexchange.com/questions/36838/why-does-the-standard-bitcoin-message-signature-include-a-magic-prefix) established it and ethereum (and other projects) just copied it.  The reason to add the lengths is to avoid a [potential length extension attack](https://en.wikipedia.org/wiki/Length_extension_attack).

Since we use sha256 too, we must implement this in the same way. Therefore, the string to be signed will be:

`result = sha256(sha256(length(prefix) . prefix . length(message) . message))
`
So please @alepop  @willclarktech  can you add the changes to the PR? This should complete the issue.

**Comment by willclarktech** [comment]
@IkerAlus How should the length be encoded? Also something like Bitcoin's `varint`?

**Comment by IkerAlus** [comment]
The main point of adding the length is that the message verifier can check that the length indeed is the original and no-one has added a padded tail to perform the attack. Therefore the length should be easily verificable. 

For simplicity, I would go with Bitcoin's implementation. But take care not to fall into issues as [those](https://github.com/ethereum/go-ethereum/issues/14794) that the ethereum implementation has

**Comment by alepop** [comment]
@willclarktech @IkerAlus PR updated with `varint` length calculation
