### ISSUE TITLE
dist-node missing?

### ISSUE THREAD

**Issue by 5an1ty** [LiskHQ/lisk-elements#686]
I'm trying to already integrate the new lisk-elements in updates for my projects to be compatible with Lisk 1.0.

However when trying to install with lisk-elements as a a github dependency I don't get a functional install:

```
    "lisk-elements": "git+https://github.com/LiskHQ/lisk-elements.git#development"
```

**Comment by willclarktech** [comment]
Hi @5anity, thanks for reporting. The reasoning for the current structure is (1) keep `dist-node` out of source control since it can be derived from the source code and is liable to get out of sync, (2) build `dist-node` when publishing to npm. We haven't explicitly planned for installations via GitHub.


Would a conditional `postinstall` build work for you? (E.g. conditional upon whether `dist-node/index.js` is present.)

**Comment by 5an1ty** [comment]
@willclarktech No need for me, I mistakenly assumed something was wrong with the npm package because the latest tag was 0.0.0. I installed the beta4 version and everything works as expected via NPM. This could still be interesting for those trying to install via github.
