### ISSUE TITLE
Verify Signature: Backward compatibility with old Prefix + Message verify process

### ISSUE THREAD

**Issue by hirishh** [LiskHQ/lisk-elements#776]
### Expected behavior
I expect to be able to verify a signed message with the old format "prefix + message" (implemented in version 1.0.0-beta.4)

There is a specific reason for this. Hardware wallets implementations (Ledger for sure) implement the old sign process with simply the message. 

In order to be able to use hardware wallets to sign and verify, it's better to support both verify processes for a while, until hw implementations will adequate to the new process.

The verify should be:

- Verify with the new process where `digest = hash(hash( prefix_length + prefix + msg_length + msg))`
- IF fails, try to verify with the old process where `digest = msg`
- Return the result

### Actual behavior
Verify fails for old signed messages

### Steps to reproduce

- Sign with Hardware wallet (Ledger for example)
- Try to verify with lisk-elements:1.0.0

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by vekexasia** [comment]
It's worth noting that due to this change in behavior introduced here https://github.com/LiskHQ/lisk-elements/pull/674 all the previously signed messages (which were valid and could be considered valid) are now marked as invalid.

This is especially important if someone had a signed message stating something valuable that is still important today.

**Comment by willclarktech** [comment]
As mentioned in [this issue](https://github.com/LiskHQ/lisk-elements/issues/673), backwards compatibility was considered and rejected because of the security sensitivity of the problem. Preventing users from accidentally signing a transaction digest via the sign message feature is completely undermined if we fall back to the old verification process.

The concern raised by @vekexasia was noted at the time, but we believe that message signing is mostly used in one-shot, short-term proof situations, and the security aspect was an overriding concern in any case.

@hirishh If you really need both verification options, you can easily construct your own conditional function making use of the different functions from `lisk-elements` and `lisk-js`.

As for the hardware wallet situation, @alepop can confirm but I believe the Trezor implementation began with the updated signing/verifying process (and the change was even instigated by that integration attempt). See https://github.com/trezor/trezor-core/pull/217

Going forward, since we have reached v1 now (signifying a level of maturity not previously present in the project) we may consider backwards compatibility more seriously (for exactly the reasons mentioned in this issue), although security concerns are always likely to take precedence.

**Comment by vekexasia** [comment]
> The concern raised by @vekexasia was noted at the time, but we believe that message signing is mostly used in one-shot, short-term proof situations, and the security aspect was an overriding concern in any case.

IMHO I believe no assumptions should be made. When people used signed messages they've shown a very creative way of using it. 

Anyway I don't think there is any security concern here as I believe hirish proposal is all about changing the `verification` routine not the signing mechanism which was, as you said, insecure.

Anyway problem remains: old signed messages (with a non-secure way) are marked as non-verified while they should, instead, marked as valid IMHO.

**Comment by alepop** [comment]
> As for the hardware wallet situation, @alepop can confirm but I believe the Trezor implementation began with the updated signing/verifying process (and the change was even instigated by that integration attempt). See trezor/trezor-core#217

confirm

**Comment by willclarktech** [comment]
> Anyway I don't think there is any security concern here as I believe hirish proposal is all about changing the verification routine not the signing mechanism which was, as you said, insecure.

In case anyone before the change was tricked into signing a transaction digest, we want those signatures to be invalid. Unfortunately that requires invalidating all such signatures. Lack of backwards compatibility here is a feature.
